[package]
name = "port_scanner_x"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = { version = "0.9.20", features = ["derive"] }
colored = "3.0.0"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.28"
port_check = "0.3.0"
tokio = { version = "1.48.0", features = ["full"] }
